name: 'dbt_training_ch'
version: '1.0.0'
profile: 'dbt_training_ch'

# Paths telling dbt where to find your files
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]

# Folder cleanup configurations
clean-targets:
  - "target"
  - "dbt_packages"

# Table build instructions
models:
  dbt_training_ch:
    +materialized: view      # Default rule: build everything as a view first
    
    staging:
      +materialized: table   # Exception 1: Build staging files as physical tables
    marts:
      +materialized: table   # Exception 2: Build final marts as physical tables

# Data quality log instructions
tests:
  +store_failures: true      # Automatically saves test records directly into ClickHouse